/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TagsImport } from './routes/tags'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TagsRoute = TagsImport.update({
  path: '/tags',
  getParentRoute: () => rootRoute,
})

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
})

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
})

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  TagsRoute,
])

/* prettier-ignore-end */
